server:
  host: 0.0.0.0
  port: 9091
  endpoints:
  authz:
    forward-auth:
      implementation: 'ForwardAuth'
      authn_strategies:
        - name: 'HeaderAuthorization'
          schemes:
            - 'Basic'
          scheme_basic_cache_lifespan: 0
        - name: 'CookieSession'

log:
  level: info

jwt_secret: ${JWT_SECRET}

default_redirection_url: https://docs.futuraaigroup.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    # Portainer (solo admin)
    - domain: portainer.docs.futuraaigroup.com
      policy: two_factor
      subject: "group:admins"

    # DocMost (admin e team)
    - domain: docs.futuraaigroup.com
      policy: two_factor

session:
  name: authelia_session
  secret: ${SESSION_SECRET}
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'
  cookies:
    - domain: 'futuraaigroup.com'
      authelia_url: 'https://auth.futuraaigroup.com'
      default_redirection_url: 'https://www.futuraaigroup.com'
      name: 'authelia_session'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1d'

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: ${STORAGE_ENCRYPTION_KEY}
  local:
    path: /config/db.sqlite3

# Configurazione per secondo fattore (TOTP)
totp:
  issuer: Futura AI Group
  period: 30
  skew: 1

# Notificatore per recupero password e registrazione TOTP
notifier:
  filesystem:
    filename: /config/notification.txt
