server:
  host: 0.0.0.0
  port: 9091

jwt_secret: ${JWT_SECRET}

default_redirection_url: https://portainer.docs.futuraagroup.com

session:
  name: authelia_session
  secret: ${SESSION_SECRET}
  expiration: 1h
  domain: docs.futuraagroup.com
  redis:
    host: redis
    port: 6379

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    # Admin full access
    - domain: "*.docs.futuraagroup.com"
      policy: two_factor
      subject:
        - group: admins

    # Docmost per editors
    - domain: docs.futuraagroup.com
      policy: two_factor
      subject:
        - group: editors

    # Docmost read-only per viewers
    - domain: docs.futuraagroup.com
      policy: one_factor
      subject:
        - group: viewers

totp:
  issuer: docs.futuraagroup.com
  period: 30
  skew: 1

notifier:
  filesystem:
    filename: /config/notification.txt
